### ISSUE TITLE
Readme does not reference audio stream

### ISSUE THREAD

**Issue by bradgyton** [joshgetter/hassio-addons#9]
Noticed the new release mentions audio support (AWESOME) but no reference in documentation as to how to enable it.

**Comment by joshgetter** [comment]
Hey @bradgyton - There are some Instructions, they're just hidden in the weeds towards the bottom under the [Adding Camera to Home Assistant](https://github.com/joshgetter/hassio-addons/tree/master/kasa-camera#adding-camera-to-home-assistant) section 😃.  The gist is that you'll need to use the RTMP stream produced by the add-on rather than the HLS stream. You can update that in your HA configuration.yaml file where you define your camera.
